### ISSUE TITLE
the obstacles  do get into Each other

### ISSUE THREAD

**Issue by Ali-Meh** [m-salek/Prozhe-Mabani-Computer#1]
as you might observed the obstacles do go just after each other some times 

i mean some times we have the obstacles with word M and S just Beside each other

**Comment by Ali-Meh** [comment]
you can fix this by setting the line 144 as following

startObj1 = x-1;

**Comment by m-salek** [comment]
Looks like you found a bug, and also mentioned a good thing to change in code (x-1 instead of x) , but it is not the fix. but I'll merge pull request for x-1.

**Comment by m-salek** [comment]
the bug fixed by adding `&& endObj1<x/2` into `else if(obj2==0)` and also setting endObj1 to 0 at first.
